export const queryKeys = {
  todos: 'todos',
  users: 'users',
  lines: 'lines',
  permission: 'permission',
  projects: 'projects',
  'user-role': 'user-role',
  'user-detail': 'user-detail',
  reception: 'reception',
  options: 'options',
  status: 'status',
  branchs: 'branchs',
  services: 'services',
  servicesList: 'servicesList',
  leads: 'leads',
  leads_Manage: 'leadsManage',
  permissionOptions: 'permissionOptions',
  permission: 'permission',
  telesales: 'telesales',
  notis: 'notis',
  countNoti: 'countNoti',
  leadsDetails: 'leadsDetails',
  leadComments: 'leadComments',
  leadHistoryCalls: 'leadHistoryCalls',
  personal: 'personal',
  team: 'team',
  authLine: 'authLine',
  adsImport: 'adsImport',
  teleStatus: 'telesaleStatus',
  appointmentmy: 'appointmentmy',
  appointmentLeadManage: 'appointmentLeadManage',
  statisticPagelead: 'statisticPagelead',
  archives: 'archives',
  contactQuality: 'contactQuality',
  contactQualityPersonal: 'contactQualityPersonal',
  statisticFanpage: 'statisticFanpage',
  dataPage: 'dataPage'
};

export const roles = {
  ALL: 'ALL',
  RECEPTION: 'RECEPTION',
  ADMIN: 'ADMIN',
  MASTER_ADMIN: 'MASTER_ADMIN',
  PAGE_LEAD: 'PAGE_LEAD',
  TELESALE: 'TELESALE',
  TELESALE_LEAD: 'TELESALE_LEAD',
  ADS_ADMIN: 'ADS_ADMIN',
  ADS: 'ADS',
  FANPAGE: 'FANPAGE',
};

export const STATUS_CALL = {
  BUSY: 'Busy',
  TERMINATED: 'Terminated',
  CANCELED: 'Canceled',
  REJECTED: 'Rejected',
};
