export const RouteBase = {
  // Home: '/',
  Dashboard: '/dashboard',
  LineList: '/lines',
  Login: '/login',
  Test: '/test',
  Permission: '/permission',
  Data: '/data',
  UserList: '/users',
  ProjectSelect: '/project-select',
  Contacts: '/contacts',
  BrandManagement: '/brand-management',
  Services: '/services',
  Projects: '/projects',
  Receptionist: '/receptionist',
  FanpageDashboard: '/fanpage-dashboard',
  Archives: '/archives',
  Report: '/report',
  Accounts: '/accounts',
  TelesaleDashboard: '/telesale-dashboard',
  Profile: '/profile',
  DailyReport: '/daily-report',
  MonthlyReport: '/monthly-report',
  KPI: '/kpi',
  AdminDailyReport: '/admin-daily-report',
  TelesaleManage: '/manage-telesale'
};
